###https://projecteuler.net/problem=12

#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:

#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28

#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

#n = 1
#trinum = 0
#result = []
#while  len(result) < 500:
#
#	trinum = trinum + n
#
#	result=[]
#	for i in range(1,trinum+1):
#		if trinum % i == 0:
#			result.append(i)
#	if len(result) >  200:
#		print(n, len(result),  end =  ' / ')
#	n = n + 1

#print(trinum)
#print(len(result))


a=0; c=0; max=0; 
while max<=500:
	c+=1; a+=c; d=0; b=0; x=1
	while a/x != b:
		if a%x==0:
			if x*x==a:
				d+=1
				break
			b=x
			d+=2
		x+=1
	if d>max:
		max=d
		print (d,a)
